[package]
name = "chronomover"
version = "0.1.2"
edition = "2024"

[dependencies]
chrono = "0.4.42"
clap = { version = "4.5.51", features = ["derive"] }
color-eyre = "0.6.5"
humantime = "2.3.0"
walkdir = "2.5.0"

[profile.release]
opt-level = 3
lto = true
debug = "line-tables-only"
